[workspace]
members = [
    "json-steroids-derive",
]

[package]
name = "json-steroids"
version = "0.3.1"
edition = "2021"
description = "Blazing fast JSON serialization and deserialization library, powered by procedural macros."
license = "MIT"

[features]
default = ["simd"]
simd = []
arrayvec = ["dep:arrayvec"]

[dependencies]
json-steroids-derive = { path = "./json-steroids-derive", version = "0.3.0"}
itoa = "1.0"
ryu = "1.0"
arrayvec = { version = "0.7", optional = true }

[dev-dependencies]
criterion = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sonic-rs = "0.5.8"

[[bench]]
name = "benchmarks"
harness = false

[[bench]]
name = "simd_benchmarks"
harness = false
required-features = ["simd"]

